---
title: "Climbing Insights"
author: Ian McDonald
output: html_notebook
---

installing packages
```{r}
install.packages("tidyverse")
install.packages("RSQLite")
install.packages("wesanderson")
install.packages("RColorBrewer")
```

loading libraries
```{r}
library("tidyverse")
library("RSQLite")
library(ggplot2)
library("RColorBrewer")
```

creating database connection and checking the table headers
```{r}
con <- dbConnect(RSQLite::SQLite(), "database.sqlite")

dbListTables(con)
dbListFields(con, "ascent")
dbListFields(con, "grade")
dbListFields(con, "method")
dbListFields(con, "user")

res <- dbGetQuery(con, "SELECT country, count(id) from user group by country order by count(id) desc limit 10;")

colorPal <- c("#712398", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#7C8A9B","#DA2391")

p<-ggplot(data=res, aes(x=reorder(country, -res$`count(id)`), y=res$`count(id)`, colour = reorder(country, -res$`count(id)`), fill = reorder(country, -res$`count(id)`))) + geom_bar(stat="identity") + xlab("Country of Residence") + ylab("Number of Climbers")  +scale_color_manual(values=colorPal, aesthetics = c("colour", "fill"), name="Country")

p

dbDisconnect(con)

```

